### ISSUE TITLE
Criar layout inicial da página home

### ISSUE THREAD

**Issue by DiegoSousaLeite** [DiegoSousaLeite/Automotive-Network-Evaluation-Board#2]
## Descrição da Issue:
Desenvolver o layout inicial para a página home do nosso site. O design deve ser responsivo e alinhado com a identidade visual da marca. A página inicial deve incluir seções para produtos em destaque, sobre a empresa, e contatos.

## Tasks:
- [x] Criar um esboço inicial do layout.
- [x] Revisar o esboço com a equipe de design.
- [x] Implementar o layout em QT.
- [x] Testar a responsividade.

## Critérios de Aceitação:
- [x] O layout deve ser visualmente atraente e alinhado.
- [x] Todas as seções devem estar claramente organizadas e acessíveis.
- [x] Deve ser fácil de navegar para os usuários.

## Ambiente:
- **Ferramentas de Design:** Qt creator
- **Tecnologias Front-end:** Qt 6

## Anexos:
![Tela Home](https://i.imgur.com/z48vnzU.png)

_Tela antiga_

## Tags:
`UI/UX`, `design`, `frontend`, `home page`
